name: stackoverflow_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  auto_route: ^0.2.2
  get_it: ^3.1.0
  injectable: ^0.2.2
  dio: ^3.0.8
  # provider: ^4.0.4

dev_dependencies:
  injectable_generator: ^0.2.2
  auto_route_generator: ^0.2.2
  build_runner: ^1.7.4
  flutter_test:
    sdk: flutter

flutter:
  assets: 
    - assets/images/
  uses-material-design: true